#!/usr/bin/env python3
"""Render the human-readable tooltip reference from tooltip_dict.json."""
from __future__ import annotations

import argparse
from pathlib import Path

from insert_tooltips import load_dict


SOURCES = """

## Definition notes

The short tooltip text favors a useful boundary over a complete textbook definition.
Definitions for the corrected high-risk terms were checked against these primary sources:

- OpenAI API reference on nondeterministic output: <https://platform.openai.com/docs/api-reference/chat/object>
- Schenker and Gentleman on confidence-interval overlap: <https://pmc.ncbi.nlm.nih.gov/articles/PMC524673/>
- Direct Preference Optimization: <https://arxiv.org/abs/2305.18290>
- Multi-Token Prediction: <https://arxiv.org/abs/2404.19737>
- Switch Transformers on sparse expert activation: <https://arxiv.org/abs/2101.03961>
"""


def render(dictionary: dict[str, str]) -> str:
    rows = [
        "# Tooltip dictionary",
        "",
        "> Generated by `blog/tools/sync_tooltip_dictionary.py` from `blog/tools/tooltip_dict.json`.",
        "> Edit the JSON source, then run the sync command. Do not edit this table by hand.",
        "",
        "| Term | Short definition |",
        "|---|---|",
    ]
    for term in sorted(dictionary, key=str.casefold):
        safe_term = term.replace("|", "\\|")
        safe_tip = dictionary[term].replace("|", "\\|")
        rows.append(f"| {safe_term} | {safe_tip} |")
    return ("\n".join(rows) + SOURCES).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    base = Path(__file__).resolve().parent
    parser.add_argument("--dict", default=str(base / "tooltip_dict.json"))
    parser.add_argument("--output", default=str(base / "tooltip-dictionary.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    expected = render(load_dict(args.dict))
    output = Path(args.output)
    if args.check:
        actual = output.read_text(encoding="utf-8") if output.exists() else ""
        if actual != expected:
            print(f"tooltip reference is stale: {output}")
            raise SystemExit(1)
        print(f"tooltip reference is current: {output}")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
