#!/usr/bin/env python3
"""Render the tooltip reference from definitions and provenance catalogs."""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from insert_tooltips import load_dict


SOURCE_PREFIXES = ("https://", "http://", "project:")


def load_sources(path: str | Path, dictionary: dict[str, str]) -> dict:
    """Load provenance groups and require every glossary term to be covered."""
    with open(path, encoding="utf-8") as fh:
        catalog = json.load(fh)
    if not isinstance(catalog, dict) or catalog.get("version") != 1:
        raise ValueError("tooltip source catalog version must be 1")
    if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", str(catalog.get("reviewed", ""))):
        raise ValueError("tooltip source catalog needs reviewed=YYYY-MM-DD")
    groups = catalog.get("groups")
    if not isinstance(groups, list) or not groups:
        raise ValueError("tooltip source catalog needs non-empty groups")

    covered: set[str] = set()
    seen_ids: set[str] = set()
    for group in groups:
        if not isinstance(group, dict):
            raise ValueError("tooltip source group must be an object")
        group_id = group.get("id")
        if not isinstance(group_id, str) or not re.fullmatch(r"[a-z0-9-]+", group_id):
            raise ValueError(f"invalid tooltip source group id: {group_id}")
        if group_id in seen_ids:
            raise ValueError(f"duplicate tooltip source group id: {group_id}")
        seen_ids.add(group_id)
        terms = group.get("terms")
        references = group.get("references")
        if not isinstance(terms, list) or not terms or not all(isinstance(x, str) for x in terms):
            raise ValueError(f"source group has invalid terms: {group_id}")
        if len(terms) != len(set(terms)):
            raise ValueError(f"source group has duplicate terms: {group_id}")
        if not isinstance(references, list) or not references:
            raise ValueError(f"source group has no references: {group_id}")
        if not all(isinstance(ref, str) and ref.startswith(SOURCE_PREFIXES) for ref in references):
            raise ValueError(f"source group has invalid reference: {group_id}")
        covered.update(terms)

    dictionary_terms = set(dictionary)
    missing = sorted(dictionary_terms - covered, key=str.casefold)
    unknown = sorted(covered - dictionary_terms, key=str.casefold)
    if missing:
        raise ValueError("tooltip terms without sources: " + ", ".join(missing))
    if unknown:
        raise ValueError("source catalog has unknown terms: " + ", ".join(unknown))
    return catalog


def render(dictionary: dict[str, str], catalog: dict | None = None) -> str:
    source_ids: dict[str, list[str]] = {term: [] for term in dictionary}
    if catalog is not None:
        for group in catalog["groups"]:
            for term in group["terms"]:
                source_ids[term].append(group["id"])

    rows = [
        "# Tooltip dictionary",
        "",
        "> Generated by `sync_tooltip_dictionary.py` from `tooltip_dict.json` and `tooltip_sources.json`.",
        "> Edit the JSON catalogs, not this generated file.",
        "> Edit those JSON sources, then run the sync command. Do not edit this table by hand.",
        "",
        "| Term | Short definition | Source group |" if catalog else "| Term | Short definition |",
        "|---|---|---|" if catalog else "|---|---|",
    ]
    for term in sorted(dictionary, key=str.casefold):
        safe_term = term.replace("|", "\\|")
        safe_tip = dictionary[term].replace("|", "\\|")
        if catalog:
            groups = ", ".join(f"[`{group_id}`](#{group_id})" for group_id in source_ids[term])
            rows.append(f"| {safe_term} | {safe_tip} | {groups} |")
        else:
            rows.append(f"| {safe_term} | {safe_tip} |")

    if catalog:
        rows.extend([
            "",
            "## Definition source groups",
            "",
            f"> Last reviewed: {catalog['reviewed']}. A source group is evidence for the terms listed under it; it is not a claim that every source uses the blog's exact Korean wording.",
        ])
        for group in sorted(catalog["groups"], key=lambda item: item["id"]):
            rows.extend(["", f"### {group['id']}", "", "Terms: " + ", ".join(f"`{term}`" for term in group["terms"]), ""])
            for reference in group["references"]:
                rows.append(f"- `{reference}`" if reference.startswith("project:") else f"- <{reference}>")
    return "\n".join(rows).rstrip() + "\n"


def main() -> None:
    parser = argparse.ArgumentParser()
    base = Path(__file__).resolve().parent
    parser.add_argument("--dict", default=str(base / "tooltip_dict.json"))
    parser.add_argument("--sources", default=str(base / "tooltip_sources.json"))
    parser.add_argument("--output", default=str(base / "tooltip-dictionary.md"))
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    dictionary = load_dict(args.dict)
    expected = render(dictionary, load_sources(args.sources, dictionary))
    output = Path(args.output)
    if args.check:
        actual = output.read_text(encoding="utf-8") if output.exists() else ""
        if actual != expected:
            print(f"tooltip reference is stale: {output}")
            raise SystemExit(1)
        print(f"tooltip reference is current: {output}")
        return
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(expected, encoding="utf-8")
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
